### ISSUE TITLE
Erro no desconto de mesas ou comandas transferidas

### ISSUE THREAD

**Issue by chsguitar1** [shiraishist/G7Dev#110]
Ao transferir uma mesa ou comanda para outra e ao receber efetuar um desconto o valor total fica incorreto, mas nao esta ficando errado no banco de dados

**Comment by eulerjacson** [comment]
Transferência de comanda: corrigido valor de status no filtro.
Desconto em comanda transferida: corrigido o calculo do total para pegar os descontos do pedido e não da venda repetidamente como estava.
