### ISSUE TITLE
Implantação do pagamento via Stone

### ISSUE THREAD

**Issue by chsguitar1** [shiraishist/G7Dev#112]
implantar comunicação e pagamento com a Stone no Gourmet 7

**Comment by mariofelesdossantosjunior** [comment]
Implementação Concluída 
Quando usuário usa Stone Pagamentos....
No inicio do sistema ... o sistema comunica com o pinpad e armazena os dados dele...
No pagamento ...
Quando usuário seleciona as formas de pagamento CARTÃO DE CREDITO / CARTÃO DE DEBITO
ao confirmar ele é redirecionado para uma tela de Pagamentos de Cartão...
onde lista as transações a serem feitas via Stone...
Cada linha da tabela representa 1 transação...
Basta Selecionar o item... Sistema comunica com Pinpad e Manda Inserir Cartão com seu respectivo valor..
Caso de Sucesso .. Transação Aprovada...
Caso de Falha - É mostrada a falha na barra de status...
