### ISSUE TITLE
Instalador

### ISSUE THREAD

**Issue by shiraishist** [shiraishist/G7Dev#2]

**Comment by chsguitar1** [comment]
gerado instalador 64 e 32, aguardar atualização do banco

**Comment by vinifor** [comment]
o script do banco fiscal já tá pronto e comitado no projeto

**Comment by chsguitar1** [comment]
instalei co m o instalador e nao deu erro o cnpj ou cpf somente numeros

**Comment by chsguitar1** [comment]
instalador 32 bits e 64 base atualizada
