### ISSUE TITLE
G7 - Item duplicado no banco

### ISSUE THREAD

**Issue by shiraishist** [shiraishist/G7Dev#67]
Ocorrência Recanto do peixe 25/09.
Ao lançar pedido no tablet, o mesmo foi inserido 2x no banco de dados e foi impresso 2x.

**Comment by mariofelesdossantosjunior** [comment]
Finalizei a implementação da  correção..
Aparentemente problema era devido ao duplo click no envio do pedido.
Implementei a função de desabilitar o ícone de enviar, apos ser clicado.
