### ISSUE TITLE
G7 - Sistema lento

### ISSUE THREAD

**Issue by shiraishist** [shiraishist/G7Dev#68]
após um determinado tempo decorrido de uso, o sistema passou a levar mais tempo para receber as vendas, chegando a 10 segundos, quando o normal é 03. Ao sair do sistema e reabrir o sistema volta ao normal.

**Comment by mariofelesdossantosjunior** [comment]
Implementei GC na parte de recebimento agrupado...

**Comment by mariofelesdossantosjunior** [comment]
Para uma maior performasse sera implementado alterações no projeto apos a reestruturação implementada.
