### ISSUE TITLE
Tablet - Erro lista de itens ao recuperar mesa

### ISSUE THREAD

**Issue by shiraishist** [shiraishist/G7Dev#69]
Lista dos itens do mapa de mesa apresenta erro de somatório qndo existe item extornado na venda, da mesma forma estes itens ao existir rolagem, a lista fica errada.

**Comment by mariofelesdossantosjunior** [comment]
Implementação concluída,  o problema ocorria devido a opção no produto de não importá-lo... Sendo que na lista de itens consumidos preciso de todos os produtos independe se eles  tem a opção de ser importado ou não
