### ISSUE TITLE
G7 - Caixa pedindo para abrir 2x

### ISSUE THREAD

**Issue by shiraishist** [shiraishist/G7Dev#72]
Movimentação dos dias 27 e 28/09 dos usuários Vilma e Viviane.

**Comment by mariofelesdossantosjunior** [comment]
Finalizei a implementação, não conseguimos encontrar erro no banco e no sistema, o que se deu pra perceber foi erro operacional deles... fiz a implementação de uma correção de dialogs que ficavam abertos por trás de outras telas.
