### ISSUE TITLE
diskentrega - erro de impressao de produto

### ISSUE THREAD

**Issue by shiraishist** [shiraishist/G7Dev#83]

**Comment by mariofelesdossantosjunior** [comment]
Mais detalhes...?

**Comment by vinifor** [comment]
Testei aqui e está funcionando normal. Não consegui reproduzir o erro

**Comment by vinifor** [comment]
Problema resolvido. Quando o cliente não tinha observação o método "substitui" dava um "nullPointerException" e não conseguia montar a impressão. Para resolver foi implementado uma condição que verifica se o cliente tem observação e caso não tenha retorna uma String vazia.

**Comment by chsguitar1** [comment]
nao subir versao atualizo aqui e subo
