### ISSUE TITLE
Liberação de mesas bloqueada em conferencia

### ISSUE THREAD

**Issue by chsguitar1** [shiraishist/G7Dev#91]

**Comment by vinifor** [comment]
foi implementada a liberação de mesas que estavam bloqueadas.
o recurso foi feito na hora de realizar um novo pedido para a mesa que está bloqueada, então uma mensagem irá aparecer pedindo para desbloquear a mesa para enviar o pedido.

OBS: o pedido pela comanda também não tinha este recurso, por isso foi implementado para ela também.
