### ISSUE TITLE
Triggers para Calculo do estoque

### ISSUE THREAD

**Issue by chsguitar1** [shiraishist/G7Dev#97]
Adequar triggers para controle de estoque médio

**Comment by vinifor** [comment]
para implementar as triggers foi verificado que necessita de campos novos nas tabelas de "itcompra", "itpedvenda", "produto" e "materia_prima" que serão utilizadas da verificar se irá momenvitar o estoque

**Comment by vinifor** [comment]
Foram criadas 3 triggers para a tabela de produto:

- produto_estoque_insert: responsável por inserir um novo registro na tabela estoque quando um novo produto for cadastrado com o controle de estoque ativo, não for montado (Combo) e não for composto (Ficha técnica);

 - produto_estoque_remove: responsável por limpar os registros da tabela de estoque do produto caso o produto tenha seu status de controle de estoque alterado para inativo;

- produto_estoque_update: responsável por inserir um novo registro na tabela estoque quando um produto for alterado para o controle de estoque ativo, não for montado (Combo) e não for composto (Ficha técnica);

**Comment by vinifor** [comment]
Foram criadas 3 triggers para a tebela de materia-prima:

- materia_prima_estoque_insert: responsável por inserir um novo registro na tabela estoque quando uma nova matéria-prima  for cadastrada com o controle de estoque ativo não for composto (Composição);

- materia_prima_estoque_remove: responsável por limpar os registros da tabela de estoque do produto caso a materia-prima  tenha seu status de controle de estoque alterado para inativo;

- materia_prima_estoque_update: responsável por inserir um novo registro na tabela estoque quando uma matéria-prima for alterada para o controle de estoque ativo e não for composto (Composição);

**Comment by vinifor** [comment]
Foi criada uma trigger a tabela de itcompra:

- itcompra_estoque: responsável por dar entrada no estoque de cada produto ou materia-prima comprados que possuam o status de controle de estoque ativo

**Comment by vinifor** [comment]
Foi criada uma trigger para a tabela de itpedvenda:

- itpedvenda_estoque: responsável por dar saída no estoque de cada produto ou matéria-prima comprados que possuam o status de controle de estoque ativo, verificando se cada um deles é montado (Combo) ou composto (Ficha Técnica para produto ou Composição para matéria-prima) ou Pizza (Sabores) e dando baixa nas suas devidas matérias-primas

**Comment by vinifor** [comment]
Foi criada uma trigger para a tabela de delitped:

- delitped_estoque: responsável por dar entrado no estoque das matérias-prima dos items composto que foram removidos da composição daquele item em especifico

**Comment by vinifor** [comment]
Foi criada uma trigger para a tabela de additped:
- additped_estoque: responsável por dar saida no estoque das matérias-prima dos items composto que foram removidos da composição daquele item em especifico
